# Generated by Django 5.0.8 on 2024-08-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageVisits',
            new_name='PageVisit',
        ),
    ]
